import type { Locale } from '../content/site';

interface ClipData {
  text: string;
  duration: number;
  words: { w: string; s: number; e: number }[];
}

// Word timings generated by scripts/generate-voice.mjs (private repo).
const clips = import.meta.glob<ClipData>('../../public/audio/*/*.json', { eager: true, import: 'default' });

export function clipDuration(locale: Locale, clip: string): number | undefined {
  return clips[`../../public/audio/${locale}/${clip}.json`]?.duration;
}

export function formatDuration(seconds: number | undefined): string {
  if (!seconds) return '';
  const s = Math.round(seconds);
  return `${Math.floor(s / 60)}:${String(s % 60).padStart(2, '0')}`;
}
