// Astro integration: after the build, hash every inline <script> and <style>
// in the generated HTML and write the full Content-Security-Policy as an HTTP
// header rule in dist/_headers. A header applies from the first byte of the
// response, so it also covers the inline bootstrap script at the top of <head>
// (a <meta> CSP only applies to what comes after it).
import { createHash } from 'node:crypto';
import { appendFile, readdir, readFile } from 'node:fs/promises';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';

const sha256 = (text) => `'sha256-${createHash('sha256').update(text, 'utf8').digest('base64')}'`;

async function htmlFiles(dir) {
  const entries = await readdir(dir, { withFileTypes: true, recursive: true });
  return entries.filter((e) => e.isFile() && e.name.endsWith('.html')).map((e) => join(e.parentPath, e.name));
}

/** @param {{ directives: string[] }} options Non-script/style directives, e.g. "default-src 'self'". */
export default function cspHeaders({ directives }) {
  return {
    name: 'csp-headers',
    hooks: {
      'astro:build:done': async ({ dir, logger }) => {
        const root = fileURLToPath(dir);
        const scripts = new Set();
        const styles = new Set();
        for (const file of await htmlFiles(root)) {
          const html = await readFile(file, 'utf8');
          for (const [, attrs, body] of html.matchAll(/<script\b([^>]*)>([\s\S]*?)<\/script>/gi)) {
            if (/\bsrc\s*=/.test(attrs)) continue; // external: covered by 'self'
            const type = /\btype\s*=\s*["']?([^"'\s>]+)/i.exec(attrs)?.[1]?.toLowerCase();
            if (type && type !== 'module' && !type.includes('javascript')) continue; // data blocks (JSON-LD) never execute
            scripts.add(sha256(body));
          }
          for (const [, body] of html.matchAll(/<style\b[^>]*>([\s\S]*?)<\/style>/gi)) styles.add(sha256(body));
        }
        const policy = [
          ...directives,
          `script-src 'self' ${[...scripts].join(' ')}`.trim(),
          `style-src 'self' ${[...styles].join(' ')}`.trim(),
          // Only CSS custom properties are set through style attributes.
          "style-src-attr 'unsafe-inline'",
        ].join('; ');
        await appendFile(join(root, '_headers'), `\n# Generated by integrations/csp-headers.mjs\n/*\n  Content-Security-Policy: ${policy}\n`);
        logger.info(`CSP header written: ${scripts.size} script and ${styles.size} style hashes`);
      },
    },
  };
}
